# enable bluetooth
CONFIG_BT=y

# enable mouse key / pointing emulation
CONFIG_ZMK_POINTING=y

# increase bluetooth signal power
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# enable deep sleep support
CONFIG_ZMK_SLEEP=y

# the keyboard disconnects from bluetooth.
# uses very little power, but it may take
# a few seconds to reconnect after waking.
# 1.800.000 ms = 30 minutes
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=1800000

# "Eager Debouncing"
# Trying to lower the input lag.
# CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=1
# CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=5

# --- DISPLAY SETTINGS ---

# enable display
CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_CUSTOM=y

# zmk-nice-oled: use nice!view (Sharp Memory LCD) mode
CONFIG_NICE_OLED_ON=n
CONFIG_NICE_EPAPER_ON=y

# disable WPM widget
CONFIG_NICE_OLED_WIDGET_WPM=n

# peripheral: static image, no animation (save battery)
CONFIG_NICE_OLED_WIDGET_ANIMATION_PERIPHERAL=n
CONFIG_NICE_OLED_WIDGET_STATIC_IMAGE_PERIPHERAL=y
CONFIG_NICE_OLED_WIDGET_STATIC_IMAGE_PERIPHERAL_VIM=y

# active modifiers (Ctrl/Shift/Alt/GUI)
CONFIG_NICE_OLED_WIDGET_MODIFIERS_INDICATORS=y

# active layer
CONFIG_NICE_OLED_WIDGET_LAYER=y

# disable HID indicators (CapsLock/NumLock/ScrollLock)
CONFIG_NICE_OLED_WIDGET_HID_INDICATORS=y
